services:
  api:
    build: .
    container_name: task_manager_api
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    networks:
      - internal_net
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "bunx prisma generate && bun src/server.ts"

  db:
    image: postgres:15-alpine
    container_name: task_manager_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

volumes:
  postgres_data:
    driver: local

networks:
  internal_net:
    driver: bridge
